### ISSUE TITLE
Firefox CSS problem

### ISSUE THREAD

**Issue by isntall** [electerious/Lychee#316]
I just upgraded to release/v3.0.0 and it looks nice

Though with it I'm getting an interesting behavior where i only see a quarter of the SVG graphics. 
I think I've tracked it down to 

>#sidebar .edit .iconic{
>	fill:rgba(255,255,255,.5);
>	-webkit-filter:drop-shadow(0 -1px 0 rgba(0,0,0,.2));
>	filter:drop-shadow(0 -1px 0 rgba(0, 0, 0, .2));
>	-webkit-transition:fill .2s ease-out;
>	transition:fill .2s ease-out
>}

and 
>#content .album .badge .iconic, #content .photo .badge .iconic {
>    fill: #FFF;
>    width: 16px;
>    filter: drop-shadow(0px -1px 0px rgba(0, 0, 0, 0.1));
>}

These are the lines that are having issues and if i turn them off Firefox has no problem.
filter:drop-shadow(0px -1px 0px rgba(0, 0, 0, 0.2))
filter: drop-shadow(0px -1px 0px rgba(0, 0, 0, 0.1));

Hopefully I'll have time to figure this out later this weekend.

**Comment by electerious** [comment]
Urg, you are right. That's not good :( I already replaced all icons with the new ones. It looks like a browser-bug. Maybe you find a solution. Otherwise we should report it to Mozilla.

**Comment by ophian** [comment]
I had this too and after playing around without too much success, I decided to enable it for Webkit only. I replaced all occurrences (~10) of .iconic filter to -webkit-filter, eg
```css
* .iconic {
    -webkit-filter: drop-shadow(0 1px 0 rgba(255, 255, 255, .03));
    /*filter: drop-shadow(0 1px 0 rgba(255,  255,  255,  .03));*/
}
```

**Comment by ophian** [comment]
Oh ...I forgot about it. 
I also changed all occurences of `overflow: scroll;` to `overflow: auto;` to get rid of unnecessary scrollbars. Same for `overflow-y:scroll`.

**Comment by electerious** [comment]
Using a prefix isn't future proof. It will work for now, but someday Webkit or Blink will drop the prefix. It also removes the wanted shadow from the icons in FF. I guess that this is a browser bug. Would be great if we can reproduce and report it.

What do you mean with *all* occurrences of `overflow: scroll;`? There's only one in `_sidebar.scss` as far as I see.

**Comment by ophian** [comment]
Yeah right, it was only one, but two for the overflow-y in `.basicModal .rows` and `.basicContext--scrollable`

**Comment by ophian** [comment]
And there was another one. 
I could not access the name and desc edit buttons in the info sidebar, since the "next event" was layed over. 
So I changed `top: 60px` to `top: 240px` in `#imageview .arrow_wrapper` (_mediaquery.scss), which works well for my purposes.

About the filter "bug" with FF. It is reproducible with latest FF, see OP above. I did not find any clear infos about this being a bug...

**Comment by ophian** [comment]
> Using a prefix isn't future proof.

Well then - I assume - we have to use this as long Mozilla behaves different.
```css
@-moz-document url-prefix() {
  header #title .iconic,
  header .button .iconic,
  #content .album .badge .iconic,
  #content .photo .badge .iconic,
  svg.iconic {
      filter: drop-shadow(7px 7px 0px rgba(255, 255, 255, 0.2));
  }
  #sidebar .edit .iconic,
  .basicContext tr td .iconic {
      filter: drop-shadow(3px 3px 0px rgba(255, 255, 255, 0.2));
  }
}
```
Did you see the IE no svg issue?

**Comment by electerious** [comment]
@ophian I fixed the arrows and the unnecessary scrollbars. Let me know if these two bugs are fixed. Filter problem still occurs. I will try to capsulate the problem and report it to Mozilla. I also realized that the following works in FF:

```scss
.iconic {
	fill: white(.5);
	//filter: drop-shadow($shadow);
	transition: fill .2s ease-out;

	use { filter: drop-shadow($shadow); }
}
```

But it only works in FF. `filter` still needs to be applied to `.iconic` in other browsers, which breaks it again.

**Comment by ophian** [comment]
I can't access it with your snippet, even if set to all selectors. I still have to use
```css
@-moz-document url-prefix() { 
	#sidebar .edit .iconic, 
	.basicContext tr td .iconic,
	header #title .iconic, 
	header .button .iconic, 
	.iconic,
	#content .album .badge .iconic,
	#content .photo .badge .iconic,
	#imageview .arrow_wrapper .iconic { filter: inherit; }
}
```
(I am not really sure why you need this shadow at all - for me that looks well without. :) )

Personally I don't think removing the z-index, which removes the next event, is a good idea for the next layer on an opened info box layer. I thought it to be very usefull to have the next event available with an open info box. It saves some time to page through an album with info opened. What do you think?
