### ISSUE TITLE
css minor no content colour

### ISSUE THREAD

**Issue by ophian** [electerious/Lychee#347]
On empty lychee start (v.3.0.0), wouldn't it be better to actually visualise the no content icon and text by colour? Currently it is just black and nearly impossible to recognise on some screens.
eg in white
```css
.no_content .iconic {
    fill: rgba(255, 255, 255, 0.9);
}
.no_content {
    color: rgba(255, 255, 255, 0.9);
    text-shadow: 0px 1px 0px rgba(255, 255, 255, 0.03);
    text-align: center;
}
```
